import { createClient } from '@supabase/supabase-js';
import { io } from 'socket.io-client';

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY);
let installed=false,realtimeSocket=null,conversations=[],activeConversationId=null,currentUserId=null,typingTimer=null,typingActive=false,videoAsFile=false,linkAsText=false,readInFlight=false,observerTimer=null,readScrollCleanup=null;
const seenIncomingMessages=new Set(),unread=new Map();
const API=import.meta.env.VITE_API_URL||'http://localhost:3001';
const UNREAD_KEY='frostlink:unread:v1';
try{const saved=JSON.parse(localStorage.getItem(UNREAD_KEY)||'{}');Object.entries(saved).forEach(([id,n])=>{if(Number(n)>0)unread.set(id,Number(n))})}catch{}
function saveUnread(){localStorage.setItem(UNREAD_KEY,JSON.stringify(Object.fromEntries(unread)))}
function unreadTotal(){return [...unread.values()].reduce((sum,n)=>sum+(Number(n)>0?Number(n):0),0)}
function unreadChats(){return [...unread.values()].filter(n=>Number(n)>0).length}
function unreadFor(id){return unread.get(id)||0}
function setUnread(id,n){if(n>0)unread.set(id,n);else unread.delete(id);saveUnread();renderUnread();updateLatest()}
function incrementUnread(id){setUnread(id,unreadFor(id)+1)}
function clearUnread(id){setUnread(id,0)}
async function token(){try{const {data}=await supabase.auth.getSession();currentUserId=data.session?.user?.id||null;return data.session?.access_token||''}catch{return ''}}
async function api(path,opt={}){const t=await token();return fetch(API+path,{...opt,headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json',...(opt.headers||{})}})}
function getMessageScroller(){return document.querySelector('.messages')}
function isNearBottom(){const e=getMessageScroller();return Boolean(e&&e.scrollHeight-e.scrollTop-e.clientHeight<180)}
async function syncMessageDom(){if(!activeConversationId)return;try{const r=await api(`/api/conversations/${encodeURIComponent(activeConversationId)}/messages`);const j=await r.json().catch(()=>({}));if(!r.ok)return;const list=Array.isArray(j.messages)?j.messages:[],els=[...document.querySelectorAll('.messages .msg')],start=Math.max(0,list.length-els.length);els.forEach((el,i)=>{const m=list[start+i];if(!m?.id)return;el.dataset.messageId=String(m.id);el.classList.toggle('mine',m.sender_id===currentUserId);el.classList.toggle('theirs',m.sender_id!==currentUserId);if(m.sender_id===currentUserId)addReadStatus(m.id,false)});if(activeConversationId&&isNearBottom())setTimeout(markIncomingRead,30)}catch(e){console.warn('Message DOM sync failed:',e.message)}}
function installReadTracking(){const el=getMessageScroller();if(!el)return;if(el.dataset.frostReadTracking==='1')return;el.dataset.frostReadTracking='1';const onScroll=()=>{if(activeConversationId&&isNearBottom())markIncomingRead()};el.addEventListener('scroll',onScroll,{passive:true});readScrollCleanup=()=>{el.removeEventListener('scroll',onScroll);if(el.dataset.frostReadTracking==='1')delete el.dataset.frostReadTracking};setTimeout(syncMessageDom,80)}
function resolveActive(){const small=document.querySelector('.chat-head small');const username=String(small?.textContent||'').trim().replace(/^@/,'');const c=conversations.find(x=>x.other?.username===username);if(c&&c.id!==activeConversationId){if(activeConversationId&&realtimeSocket)realtimeSocket.emit('leave-conversation',activeConversationId);if(readScrollCleanup)readScrollCleanup();activeConversationId=c.id;if(realtimeSocket?.connected)realtimeSocket.emit('join-conversation',c.id);setTimeout(syncMessageDom,120)}}
function renderUnread(){const buttons=[...document.querySelectorAll('.conversation-list .conversation:not(.request-conversation)')];const chats=conversations.slice(0,buttons.length);buttons.forEach((b,i)=>{const n=chats[i]?unreadFor(chats[i].id):0;let badge=b.querySelector('.frost-unread-badge');if(!badge){badge=document.createElement('em');badge.className='frost-unread-badge';b.appendChild(badge)}badge.textContent=n>0?String(n):'';badge.hidden=n<1;b.classList.toggle('has-unread',n>0)});const count=unreadChats();document.title=count>0?`(${count}) Frostlink`:'Frostlink'}
function updateLatest(){const btn=document.querySelector('.latest');if(!btn)return;const n=unreadFor(activeConversationId);btn.textContent=`↓ ${n} ${n===1?'message':'messages'}`;btn.hidden=n<1}
function addTypingUi(){if(document.getElementById('frost-typing-indicator'))return;const chat=document.querySelector('.chat');if(!chat)return;const el=document.createElement('div');el.id='frost-typing-indicator';el.className='frost-typing-indicator';el.setAttribute('aria-live','polite');chat.appendChild(el);const style=document.createElement('style');style.textContent=`#frost-typing-indicator{position:absolute;left:18px;bottom:82px;z-index:8;min-height:20px;padding:5px 10px;border-radius:999px;background:rgba(8,16,30,.78);backdrop-filter:blur(10px);color:#bfe9ff;font-size:12px;pointer-events:none;opacity:0;transform:translateY(4px);transition:opacity .16s,transform .16s}.frost-typing-indicator.show{opacity:1;transform:none}.frost-read-status{margin-left:6px;font-size:11px;letter-spacing:.02em;color:#79b9ff}.frost-read-status.read{color:#56efbd}.frost-video-mode{display:inline-flex!important;align-items:center;justify-content:center;gap:4px;min-width:34px}.frost-video-mode.active{color:#56efbd!important}.frost-video-mode svg{display:none!important}.frost-unread-badge{margin-left:auto;min-width:20px;height:20px;padding:0 6px;border-radius:999px;display:inline-flex;align-items:center;justify-content:center;background:#56efbd;color:#06131b;font-size:11px;font-style:normal;font-weight:800}.conversation.has-unread .conv-copy b{font-weight:800}.frost-link-actions{display:flex;gap:6px;margin-top:6px;flex-wrap:wrap}.frost-link-action{border:0;border-radius:8px;padding:4px 8px;font:inherit;font-size:11px;cursor:pointer;background:rgba(127,190,255,.12);color:inherit}.frost-link-action:hover{background:rgba(127,190,255,.22)}`;document.head.appendChild(style)}
function setTyping(text){const el=document.getElementById('frost-typing-indicator');if(!el)return;el.textContent=text||'';el.classList.toggle('show',Boolean(text))}
function addReadStatus(msgId,read=false){const el=document.querySelector(`.msg.mine[data-message-id="${CSS.escape(String(msgId))}"]`);if(!el)return;let status=el.querySelector('.frost-read-status');if(!status){status=document.createElement('span');status.className='frost-read-status';const host=el.querySelector('.meta')||el;host.appendChild(status)}status.textContent=read?'✓✓':'✓';status.title=read?'Read':'Sent';status.classList.toggle('read',read)}
async function markIncomingRead(){if(readInFlight||!activeConversationId||!isNearBottom())return;const conversationId=activeConversationId;let incoming=[...document.querySelectorAll('.messages .msg.theirs:not([data-frost-read])')].filter(el=>el.dataset.messageId).map(el=>{el.dataset.frostRead='1';return el.dataset.messageId}).filter(Boolean);if(!incoming.length){clearUnread(conversationId);return}clearUnread(conversationId);readInFlight=true;try{await Promise.all(incoming.map(id=>new Promise(resolve=>{if(!realtimeSocket?.connected){resolve(false);return}let settled=false;const finish=ok=>{if(settled)return;settled=true;clearTimeout(timer);resolve(ok)};const timer=setTimeout(()=>finish(false),1500);realtimeSocket.emit('message:read',{message_id:id},ack=>finish(Boolean(ack?.ok)))}).then(async ok=>{if(ok)return;const r=await api(`/api/messages/${encodeURIComponent(id)}/read`,{method:'POST',body:'{}'});if(!r.ok)throw Error((await r.json().catch(()=>({}))).error||`Request failed (${r.status})`)}).catch(e=>{const el=document.querySelector(`.msg.theirs[data-message-id="${CSS.escape(String(id))}"]`);if(el)delete el.dataset.frostRead;console.warn('Mark read failed:',e.message)})))}finally{readInFlight=false;if(activeConversationId===conversationId&&isNearBottom())setTimeout(()=>markIncomingRead(),0)}}
async function syncMessageDomIdsOnly(){if(!activeConversationId)return;try{const r=await api(`/api/conversations/${encodeURIComponent(activeConversationId)}/messages`);const j=await r.json().catch(()=>({}));if(!r.ok)return;const list=Array.isArray(j.messages)?j.messages:[],els=[...document.querySelectorAll('.messages .msg')],start=Math.max(0,list.length-els.length);els.forEach((el,i)=>{const m=list[start+i];if(m?.id){el.dataset.messageId=String(m.id);el.classList.toggle('mine',m.sender_id===currentUserId);el.classList.toggle('theirs',m.sender_id!==currentUserId)}})}catch{}}
function installTyping(){const input=document.querySelector('.composer input,.composer textarea');if(!input||input.dataset.frostTyping)return;input.dataset.frostTyping='1';const emitStart=()=>{if(!activeConversationId||!realtimeSocket?.connected)return;if(!typingActive){typingActive=true;realtimeSocket.emit('typing:start',activeConversationId)}clearTimeout(typingTimer);typingTimer=setTimeout(emitStop,900)};const emitStop=()=>{clearTimeout(typingTimer);if(typingActive&&realtimeSocket?.connected)realtimeSocket.emit('typing:stop',activeConversationId);typingActive=false;setTyping('')};input.addEventListener('input',()=>{if(!input.disabled)emitStart()});input.addEventListener('blur',emitStop);window.addEventListener('beforeunload',emitStop)}
function installMediaMode(){const btn=[...document.querySelectorAll('.composer button')].find(b=>b.getAttribute('title')==='Embed');if(btn&&!btn.dataset.frostMediaMode){btn.dataset.frostMediaMode='1';btn.classList.add('frost-video-mode');btn.setAttribute('title','Send link as normal text');btn.setAttribute('aria-label','Send link as normal text');btn.innerHTML='✓';btn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();e.stopPropagation();linkAsText=!linkAsText;window.__frostLinkAsText=linkAsText;btn.classList.toggle('active',linkAsText);btn.setAttribute('aria-pressed',String(linkAsText));btn.setAttribute('title',linkAsText?'Link will send as normal text':'Supported links will send as playable embeds')},true)}}
const youtubeUrl=/^(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:watch\?v=|shorts\/|embed\/)|youtu\.be\/)[A-Za-z0-9_-]{6,}(?:[?&][^\s]*)?$/i;
const vimeoUrl=/^(?:https?:\/\/)?(?:www\.)?vimeo\.com\/\d+(?:[?#].*)?$/i;
const directVideo=/^https?:\/\/[^\s]+\.(?:mp4|webm|mov|m4v|ogv)(?:[?#].*)?$/i;
function normalizeMediaUrl(value){return String(value||'').trim().replace(/[),.!?;:]+$/,'')}
function youtubeEmbedUrl(value){try{const clean=normalizeMediaUrl(value),u=new URL(/^https?:/i.test(clean)?clean:`https://${clean}`);const host=u.hostname.toLowerCase().replace(/^www\./,'');let id='';if(host==='youtu.be')id=u.pathname.split('/').filter(Boolean)[0]||'';else if(host==='youtube.com'||host==='m.youtube.com'){const parts=u.pathname.split('/').filter(Boolean);if(u.pathname==='/watch')id=u.searchParams.get('v')||'';else if(parts[0]==='shorts'||parts[0]==='embed')id=parts[1]||''}if(!/^[A-Za-z0-9_-]{6,}$/.test(id))return null;return `https://www.youtube-nocookie.com/embed/${encodeURIComponent(id)}?rel=0&modestbranding=1`}catch{return null}}
function mediaEmbed(value){const clean=normalizeMediaUrl(value);if(youtubeUrl.test(clean)){const embedUrl=youtubeEmbedUrl(clean);if(!embedUrl)return null;return {type:'embed',url:embedUrl,originalUrl:/^https?:/i.test(clean)?clean:`https://${clean}`,provider:'youtube'}}if(vimeoUrl.test(clean)){const original=/^https?:/i.test(clean)?clean:`https://${clean}`;const id=original.match(/vimeo\.com\/(\d+)/i)?.[1];if(!id)return null;return {type:'embed',url:`https://player.vimeo.com/video/${id}`,originalUrl:original,provider:'vimeo'}}return null}
function installTextLinkActions(){document.querySelectorAll('.messages .msg').forEach(msg=>{if(msg.dataset.frostLinkActions==='1')return;const text=String(msg.textContent||'').trim();if(!/^https?:\/\/[^\s]+$/i.test(text))return;const url=normalizeMediaUrl(text);if(!/^https?:\/\//i.test(url))return;msg.dataset.frostLinkActions='1';const actions=document.createElement('div');actions.className='frost-link-actions';const open=document.createElement('button');open.type='button';open.className='frost-link-action';open.textContent='Open in new tab';open.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();window.open(url,'_blank','noopener,noreferrer')});const copy=document.createElement('button');copy.type='button';copy.className='frost-link-action';copy.textContent='Copy link';copy.addEventListener('click',async e=>{e.preventDefault();e.stopPropagation();try{await navigator.clipboard.writeText(url);copy.textContent='Copied';setTimeout(()=>copy.textContent='Copy link',1000)}catch{const ta=document.createElement('textarea');ta.value=url;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();copy.textContent='Copied';setTimeout(()=>copy.textContent='Copy link',1000)}});actions.append(open,copy);msg.appendChild(actions)})}
function installFetchMode(){if(window.__frostFetchWrapped)return;window.__frostFetchWrapped=true;const nativeFetch=window.fetch.bind(window);window.fetch=async function(resource,options){const url=typeof resource==='string'?resource:resource?.url||'';if(/\/api\/conversations\/[^/]+\/messages$/.test(url)&&options?.method?.toUpperCase()==='POST'&&typeof options.body==='string'){try{const body=JSON.parse(options.body);const text=String(body.body||'').trim();const media=body.type==='text'?mediaEmbed(text):null;const direct=body.type==='text'?directVideo.test(normalizeMediaUrl(text)):false;if(media&&!linkAsText){body.type='embed';body.body=media.url;body.payload={...(body.payload||{}),url:media.url,embedUrl:media.url,original_url:media.originalUrl,provider:media.provider};options={...options,body:JSON.stringify(body)}}else if(direct){const videoUrl=normalizeMediaUrl(text);body.type=window.__frostVideoAsFile?'file':'video';body.body=null;body.payload={...(body.payload||{}),url:videoUrl,mime:'video/*',name:videoUrl.split('/').pop().split(/[?#]/)[0]||'video'};options={...options,body:JSON.stringify(body)}}else if(window.__frostVideoAsFile&&body.type==='video'){body.type='file';body.payload={...(body.payload||{}),sendAsFile:true};options={...options,body:JSON.stringify(body)}}if(window.__frostVideoAsFile){window.__frostVideoAsFile=false;videoAsFile=false;const toggle=[...document.querySelectorAll('.composer button')].find(b=>b.dataset.frostMediaMode);if(toggle&&!linkAsText){toggle.classList.remove('active');toggle.setAttribute('aria-pressed','false')}}}catch(e){console.warn('Media send enhancement failed:',e.message)}}return nativeFetch(resource,options)}}
function installSocket(){if(realtimeSocket)return;token().then(t=>{if(!t)return;realtimeSocket=io(API,{auth:{accessToken:t},transports:['websocket','polling'],reconnection:true});realtimeSocket.on('connect',()=>{resolveActive();if(activeConversationId)realtimeSocket.emit('join-conversation',activeConversationId)});const handleTyping=x=>{if(x?.conversation_id!==activeConversationId||x.user_id===currentUserId)return;const other=conversations.find(c=>c.id===activeConversationId)?.other;setTyping(x.active?`${other?.display_name||other?.username||'Someone'} is typing…`:'')};realtimeSocket.on('typing',handleTyping);realtimeSocket.on('typing:start',x=>handleTyping({...x,active:true}));realtimeSocket.on('typing:stop',x=>handleTyping({...x,active:false}));realtimeSocket.on('message:read',x=>{if(x?.conversation_id===activeConversationId&&x.message_id)addReadStatus(x.message_id,true)});realtimeSocket.on('message:new',m=>{if(!m?.conversation_id||m.sender_id===currentUserId||!m.id)return;if(seenIncomingMessages.has(m.id))return;seenIncomingMessages.add(m.id);if(seenIncomingMessages.size>1000)seenIncomingMessages.delete(seenIncomingMessages.values().next().value);if(m.conversation_id!==activeConversationId){incrementUnread(m.conversation_id)}else if(isNearBottom()){clearUnread(activeConversationId);setTimeout(syncMessageDom,120)}else{incrementUnread(activeConversationId)}});realtimeSocket.on('reaction:update',r=>{});setTimeout(()=>{resolveActive();installReadTracking()},500);setTimeout(()=>{loadConversations();},800)}).catch(()=>{})}
async function loadConversations(){try{const r=await api('/api/conversations');const j=await r.json().catch(()=>({}));if(!r.ok)return;conversations=Array.isArray(j.conversations)?j.conversations:[];renderUnread();resolveActive()}catch{}}
function install(){if(installed)return;installed=true;const observer=new MutationObserver(()=>{clearTimeout(observerTimer);observerTimer=setTimeout(()=>{loadConversations();installReadTracking();installTyping();installMediaMode();installTextLinkActions();updateLatest()},80)});observer.observe(document.body,{childList:true,subtree:true});setTimeout(()=>{loadConversations();installReadTracking();installTyping();installMediaMode();installTextLinkActions()},200);installSocket()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
