import { createClient } from '@supabase/supabase-js';

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY);
const API=import.meta.env.VITE_API_URL||'http://localhost:3001';
let installed=false;
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
async function session(){return (await supabase.auth.getSession()).data.session}
async function api(path,opt={}){const s=await session();const r=await fetch(API+path,{...opt,headers:{Authorization:`Bearer ${s?.access_token||''}`,'Content-Type':'application/json',...(opt.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`Request failed (${r.status})`);return j}
async function conversations(){return (await api('/api/conversations')).conversations||[]}
function activeName(){return document.querySelector('.chat-head h2')?.textContent?.trim()}
async function resolveActive(){const name=activeName();if(!name)return null;return (await conversations()).find(c=>(c.other?.display_name||c.other?.username||c.title||'Conversation')===name)||null}
function toast(msg){let d=document.getElementById('fx-live-toast');if(!d){d=document.createElement('div');d.id='fx-live-toast';d.style.cssText='position:fixed;right:20px;bottom:20px;z-index:99999;padding:10px 14px;border-radius:12px;background:#071b28ee;color:#eafaff;border:1px solid #6bdcff44;box-shadow:0 10px 35px #0008;font:13px system-ui';document.body.appendChild(d)}d.textContent=msg;d.hidden=false;clearTimeout(d._t);d._t=setTimeout(()=>d.hidden=true,2200)}
async function loadBg(){try{const r=indexedDB.open('frostlink-local',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('kv'))r.result.createObjectStore('kv')};r.onsuccess=()=>{const q=r.result.transaction('kv','readonly').objectStore('kv').get('background');q.onsuccess=()=>{if(!q.result)return;const u=URL.createObjectURL(q.result),app=document.querySelector('.app');if(app){app.style.backgroundImage=`linear-gradient(#0007,#0007),url(${u})`;app.style.backgroundSize='cover';app.style.backgroundPosition='center';app.style.backgroundAttachment='fixed'}}}}catch{}}
function persistTheme(){const app=document.querySelector('.app');if(!app)return;const saved=localStorage.getItem('frostlink-theme-bg');if(saved){app.classList.remove('bg-aurora','bg-midnight','bg-ice');app.classList.add('bg-'+saved)}new MutationObserver(()=>{const cls=[...app.classList].find(x=>x.startsWith('bg-'));if(cls)localStorage.setItem('frostlink-theme-bg',cls.slice(3))}).observe(app,{attributes:true,attributeFilter:['class']})}
function starKey(conversationId,messageId){return `frostlink-star:${conversationId}:${messageId}`}
async function openStars(){try{const c=await resolveActive();const x=await api('/api/starred-items'+(c?`?conversation_id=${encodeURIComponent(c.id)}`:''));let items=x.items||[];if(c){items=items.filter(i=>i.message?.conversation_id===c.id||i.conversation_id===c.id)}items=items.filter(i=>!localStorage.getItem(starKey(c?.id||i.message?.conversation_id||'',i.message_id||'')));let d=document.getElementById('fx-stars');if(!d){d=document.createElement('div');d.id='fx-stars';d.style.cssText='position:fixed;z-index:4000;right:20px;top:78px;width:min(430px,calc(100vw - 28px));max-height:calc(100vh - 110px);overflow:auto;padding:16px;border-radius:18px;background:#061522f7;border:1px solid #6bdcff33;color:#eafaff;box-shadow:0 24px 90px #000b;font:13px system-ui';document.body.appendChild(d)}d.innerHTML=`<button id="fxStarsClose" style="float:right">×</button><h3>Starred messages${c?' · '+esc(activeName()):''}</h3>`+(items.length?items.map(i=>`<button data-star-id="${esc(i.message_id||'')}" style="display:block;width:100%;text-align:left;margin:7px 0;padding:10px;border:1px solid #ffffff10;border-radius:10px;background:#ffffff08;color:#eafaff"><b>${esc(i.message?.sender?.display_name||'User')}</b><small style="display:block;opacity:.7">${esc(i.message?.body||i.message?.payload?.name||i.message?.type||'Starred message')}</small></button>`).join(''):'<div style="opacity:.7;padding:20px 0">No starred messages in this conversation yet.</div>');d.querySelector('#fxStarsClose').onclick=()=>d.remove();d.querySelectorAll('[data-star-id]').forEach(b=>b.onclick=()=>{document.querySelector(`.messages .msg[data-message-id="${CSS.escape(b.dataset.starId)}"]`)?.scrollIntoView({behavior:'smooth',block:'center'});d.remove()})}catch(e){toast('Starred messages failed: '+e.message)}}
async function starMessage(btn){const art=btn.closest('.msg'),id=art?.dataset.messageId;if(!id)return toast('Message is not ready to sync yet.');const c=await resolveActive();if(!c)return toast('Open a direct chat first.');const key=starKey(c.id,id);const hidden=!!localStorage.getItem(key);try{const x=await api('/api/starred-items',{method:'POST',body:JSON.stringify({message_id:id})});if(x.removed){localStorage.removeItem(key);btn.classList.remove('star-active');btn.setAttribute('title','Star message');toast('Unstarred')}else{localStorage.setItem(key,'1');btn.classList.add('star-active');btn.setAttribute('title','Unstar message');toast('Starred for this direct chat')}}catch(e){toast('Star failed: '+e.message)}}
async function embedBox(){const input=prompt('Paste a URL or iframe embed code:');if(!input)return;try{const x=await api('/api/embeds/parse',{method:'POST',body:JSON.stringify({input})}),e=x.embed;const r=prompt('Display format: 16:9, 9:16, 1:1 or 4:5','16:9');if(!['16:9','9:16','1:1','4:5'].includes(r))return toast('Use 16:9, 9:16, 1:1 or 4:5');e.aspectRatio=r;const c=await resolveActive();if(!c)throw Error('Open a direct chat first.');await api(`/api/conversations/${c.id}/messages`,{method:'POST',body:JSON.stringify({type:'embed',payload:e})});toast('Embed sent')}catch(e){toast(e.message)}}
function installHooks(){if(installed)return;installed=true;document.addEventListener('click',async e=>{const star=e.target.closest('button[title="Star message"],button[title="Unstar message"]');if(star){e.preventDefault();e.stopPropagation();await starMessage(star);return}const topStar=e.target.closest('.top-actions button:first-of-type');if(topStar){e.preventDefault();e.stopPropagation();openStars();return}const embed=e.target.closest('button[title="Embed"]');if(embed){e.preventDefault();e.stopPropagation();embedBox();return}},true)}
function boot(){const wait=()=>{if(document.querySelector('.app')){persistTheme();loadBg();installHooks()}else setTimeout(wait,250)};wait()}
boot();
