import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {io} from 'socket.io-client';
import {Search,Star,Settings,Plus,Smile,Paperclip,Send,Music2,Play,Pause,Volume2,Upload,Image as ImageIcon,FileText,Video,Link2,X,Check,CheckCheck,ChevronDown,UserPlus,Inbox,LogOut,MoreHorizontal,Maximize2,Minimize2} from 'lucide-react';
import './styles.css';

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY);
const API=import.meta.env.VITE_API_URL||'http://localhost:3001';
const QUICK=['❤️','😂','👍','😮','💀'];
const fmt=(d)=>new Date(d).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
const typeOf=f=>f.type.startsWith('image/')?'image':f.type.startsWith('video/')?'video':f.type.startsWith('audio/')?'sound':f.type==='application/pdf'?'file':'file';

function App(){
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[convos,setConvos]=useState([]),[active,setActive]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(''),[search,setSearch]=useState(''),[users,setUsers]=useState([]),[requests,setRequests]=useState([]),[panel,setPanel]=useState(null),[preview,setPreview]=useState(null),[imageViewer,setImageViewer]=useState(null),[latest,setLatest]=useState(0),[nearBottom,setNearBottom]=useState(true),[themeBg,setThemeBg]=useState('aurora'),[welcome,setWelcome]=useState(null),[music,setMusic]=useState([]),[currentTrack,setCurrentTrack]=useState(null),[playing,setPlaying]=useState(false),[reactionMode,setReactionMode]=useState(false);
 const socket=useRef(null), audio=useRef(null), listRef=useRef(null), fileRef=useRef(null), imageReactionRef=useRef(null), lastIncoming=useRef(0);
 const token=()=>session?.access_token;
 const api=async(path,opt={})=>{const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...(opt.headers||{})}}); const j=await r.json().catch(()=>({})); if(!r.ok)throw new Error(j.error||'Request failed'); return j;};
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data:l}=supabase.auth.onAuthStateChange((_,s)=>setSession(s)); return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session)return; loadProfile(); loadConvos(); loadRequests(); socket.current=io(API,{auth:{accessToken:session.access_token}}); socket.current.on('message:new',m=>{setMessages(x=>m.conversation_id===active?.id?[...x,m]:x); loadConvos(); if(m.sender_id!==session.user.id){if(nearBottom) setTimeout(()=>scrollBottom(),40); else setLatest(n=>n+1)}}); socket.current.on('reaction:update',r=>setMessages(x=>x.map(m=>m.id===r.message_id?{...m,reactions:[...(m.reactions||[]).filter(q=>!(q.user_id===r.user_id&&q.kind===r.kind)),r]}:m))); return()=>socket.current?.disconnect()},[session]);
 useEffect(()=>{if(active){loadMessages(active.id);socket.current?.emit('join-conversation',active.id);setLatest(0)} return()=>active&&socket.current?.emit('leave-conversation',active.id)},[active?.id]);
 useEffect(()=>{if(search.trim().length<2){setUsers([]);return} const t=setTimeout(()=>api('/api/users/search?q='+encodeURIComponent(search)).then(x=>setUsers(x.users)).catch(()=>{}),250);return()=>clearTimeout(t)},[search]);
 useEffect(()=>{const on=()=>{if(document.visibilityState==='visible')playWelcome()}; window.addEventListener('pointerdown',on,{once:true}); return()=>window.removeEventListener('pointerdown',on)},[welcome]);
 async function loadProfile(){const {data}=await supabase.from('profiles').select('*').eq('id',session.user.id).single();setProfile(data)}
 async function loadConvos(){try{setConvos((await api('/api/conversations')).conversations)}catch{}}
 async function loadMessages(id){try{const x=await api(`/api/conversations/${id}/messages`);setMessages(x.messages);setTimeout(scrollBottom,0)}catch{}}
 async function loadRequests(){try{setRequests((await api('/api/message-requests')).requests)}catch{}}
 function scrollBottom(){const e=listRef.current;if(e)e.scrollTo({top:e.scrollHeight,behavior:'smooth'});setLatest(0)}
 function onScroll(){const e=listRef.current;if(!e)return;const near=e.scrollHeight-e.scrollTop-e.clientHeight<180;setNearBottom(near);if(near)setLatest(0)}
 async function send(type='text',body=null,payload={}){if(!active)return; window.__frostlinkActiveConversation=active.id;if(type==='text'&&!text.trim())return;try{await api(`/api/conversations/${active.id}/messages`,{method:'POST',body:JSON.stringify({type,body:type==='text'?text.trim():body,payload})});if(type==='text')setText('')}catch(e){alert(e.message)}}
 async function sendFile(file){const local=URL.createObjectURL(file);if(reactionMode&&imageReactionRef.current){await reactImage(file);setReactionMode(false);return}setPreview({file,url:local});}
 async function confirmFile(){if(!preview)return; const {file}=preview; const t=typeOf(file); await send(t,null,{name:file.name,size:file.size,mime:file.type,localPreview:preview.url}); setPreview(null)}
 async function reactImage(file){if(!imageReactionRef.current)return; const id=imageReactionRef.current;const local=URL.createObjectURL(file); await api(`/api/messages/${id}/reactions`,{method:'POST',body:JSON.stringify({kind:'image',value:local})}); imageReactionRef.current=null;setPreview(null)}
 async function sendReaction(id,emoji){await api(`/api/messages/${id}/reactions`,{method:'POST',body:JSON.stringify({kind:'emoji',value:emoji})})}
 async function markVisible(m){if(m.sender_id===session.user.id)return;try{await api(`/api/messages/${m.id}/read`,{method:'POST'})}catch{}}
 async function requestUser(u){const initial=prompt(`Message to @${u.username} (optional):`)??'';try{await api('/api/message-requests',{method:'POST',body:JSON.stringify({recipient_id:u.id,initial_message:initial})});alert('Message request sent.')}catch(e){alert(e.message)}}
 async function handleRequest(id,action){try{const x=await api(`/api/message-requests/${id}/${action}`,{method:'POST'});await loadRequests();await loadConvos();if(x.conversation_id){const c=convos.find(q=>q.id===x.conversation_id);if(c)setActive(c)}}catch(e){alert(e.message)}}
 async function doEmbed(){const input=prompt('Paste a URL or iframe embed code:');if(!input)return;try{const {embed}=await api('/api/embeds/parse',{method:'POST',body:JSON.stringify({input})});setPreview({embed})}catch(e){alert(e.message)}}
 async function saveWelcome(file){if(file.size<1)return;const url=URL.createObjectURL(file);setWelcome({name:file.name,url});}
 function playWelcome(){if(!welcome)return;const a=new Audio(welcome.url);a.volume=.45;a.play().catch(()=>{});}
 function playTrack(track){if(audio.current?.src!==track.url){audio.current?.pause();audio.current=new Audio(track.url);audio.current.onended=()=>setPlaying(false)} if(audio.current.paused){audio.current.play();setPlaying(true)}else{audio.current.pause();setPlaying(false)}setCurrentTrack(track)}
 const currentName=active?.other?.display_name||active?.other?.username||active?.title||'Conversation';
 if(!session)return <Login/>;
 return <div className={`app bg-${themeBg}`}>
   <header className="topbar glass"><div className="brand"><div className="snow">❄</div><div><b>FROSTLINK</b><small>PRIVATE CONVERSATIONS</small></div></div><div className="top-actions"><span className="status"><i/> CONNECTED</span><button onClick={()=>setPanel('star')}><Star/></button><button onClick={()=>setPanel('requests')} className="icon-badge"><Inbox/>{requests.length>0&&<em>{requests.length}</em>}</button><button onClick={()=>setPanel('settings')}><Settings/></button></div></header>
   <main className="workspace glass"><aside className="sidebar"><div className="side-head"><h2>Messages</h2><button onClick={()=>setPanel('requests')}><Inbox/></button></div><div className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search people or usernames..."/></div>{users.length>0&&<div className="user-results">{users.map(u=><button key={u.id} onClick={()=>requestUser(u)}><Avatar p={u}/><span><b>{u.display_name}</b><small>@{u.username}</small></span><UserPlus/></button>)}</div>}<div className="conversation-list">{convos.map(c=><button className={active?.id===c.id?'conversation active':'conversation'} key={c.id} onClick={()=>setActive(c)}><Avatar p={c.other}/><span className="conv-copy"><b>{c.other?.display_name||c.title||'Conversation'}</b><small>{c.last?.body||c.last?.type||'No messages yet'}</small></span><time>{c.last?.created_at?fmt(c.last.created_at):''}</time></button>)}{convos.length===0&&<div className="empty">Search a username to start a conversation.</div>}</div></aside>
   <section className="chat"><div className="chat-head"><div><h2>{currentName}</h2><small>{active?.other?`@${active.other.username}`:'Select a conversation'}</small></div><div className="chat-actions"><button><Search/></button><button><MoreHorizontal/></button></div></div>
   <div className="messages" ref={listRef} onScroll={onScroll}>{messages.map(m=><Message key={m.id} m={m} me={m.sender_id===session.user.id} onStar={()=>setPanel('star')} onReact={e=>sendReaction(m.id,e)} onImageReact={()=>{imageReactionRef.current=m.id;setReactionMode(true);fileRef.current?.click()}} onOpenImage={url=>setImageViewer(url)} onVisible={()=>markVisible(m)}/>)}</div>
   {latest>0&&!nearBottom&&<button className="latest" onClick={scrollBottom}>↓ {latest} {latest===1?'message':'messages'}</button>}
   <div className="composer-wrap"><div className="composer"><button onClick={()=>fileRef.current?.click()} title="Files"><Plus/></button><button onClick={()=>setPanel('emoji')} title="Emoji"><Smile/></button><button onClick={()=>setPanel('gif')} title="GIF" className="gif-button"><span>GIF</span></button><button onClick={()=>setPanel('edit')} title="Edit image"><ImageIcon/></button><button onClick={()=>setPanel('sound')} title="Sounds"><Volume2/></button><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Write a message..."/><button onClick={doEmbed} title="Embed"><Link2/></button><button onClick={()=>setPanel('music')} title="Music"><Music2/></button><button className="send" onClick={()=>send()}><Send/></button></div><small>Enter sends · Shift+Enter adds a line · drop files anywhere · messages, media, embeds and reactions are supported</small></div>
   </section></main>
   <input ref={fileRef} type="file" multiple hidden onChange={e=>e.target.files[0]&&sendFile(e.target.files[0])}/>
   {panel&&<Panel panel={panel} setPanel={setPanel} requests={requests} handleRequest={handleRequest} onEmoji={e=>{setText(t=>t+e);setPanel(null)}} onMusicUpload={saveWelcome} music={music} setMusic={setMusic} currentTrack={currentTrack} playing={playing} playTrack={playTrack} onWelcome={saveWelcome} api={api} />}
   {preview&&<PreviewModal data={preview} close={()=>setPreview(null)} confirm={preview.embed?()=>{send('embed',null,preview.embed);setPreview(null)}:confirmFile}/>}
   {imageViewer&&<div className="modal-backdrop" onClick={()=>setImageViewer(null)}><div className="image-viewer glass" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setImageViewer(null)}><X/></button><img src={imageViewer}/></div></div>}
 </div>
}

function Login(){return <div className="login bg-aurora"><div className="login-card glass"><div className="snow big">❄</div><h1>FROSTLINK</h1><p>Private conversations, media and moments.</p><button onClick={()=>supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin}})}>Continue with Google</button><small>Secure sign-in powered by Supabase</small></div></div>}
function Avatar({p}){return p?.avatar_url?<img className="avatar" src={p.avatar_url}/>:<div className="avatar fallback">{(p?.display_name||p?.username||'?')[0].toUpperCase()}</div>}
function Message({m,me,onStar,onReact,onImageReact,onOpenImage,onVisible}){const [show,setShow]=useState(false);useEffect(()=>{if(!me)onVisible()},[]);const payload=m.payload||{};return <article className={`msg ${me?'mine':'theirs'}`}><Avatar p={m.sender}/><div className="bubble-wrap"><div className="meta"><b>{m.sender?.display_name||'User'}</b><time>{fmt(m.created_at)}</time></div><div className="bubble" onMouseEnter={()=>setShow(true)}>{m.type==='text'&&<p>{m.body}</p>}{m.type==='image'&&<img src={payload.localPreview||payload.url} onClick={()=>onOpenImage(payload.localPreview||payload.url)}/>} {m.type==='video'&&<video controls src={payload.localPreview||payload.url}/>} {m.type==='sound'&&<div className="audio-card"><Volume2/><span>{payload.name||'Audio'}</span><button><Play/></button></div>} {m.type==='file'&&<div className="file-card"><FileText/><span>{payload.name||'File'}</span></div>} {m.type==='embed'&&<EmbedView data={payload}/>} {m.type==='gif'&&<img src={payload.url}/>}</div><div className="message-tools"><button onClick={()=>onReact(QUICK[0])}>❤️</button><button onClick={onStar}><Star/></button><button onClick={()=>setShow(!show)}><MoreHorizontal/></button></div>{m.reactions?.length>0&&<div className="reactions">{m.reactions.map(r=>r.kind==='image'?<button key={r.id} className="reaction-img" onClick={()=>onOpenImage(r.value)}><img src={r.value}/></button>:<span key={r.id}>{r.value}</span>)}</div>}<div className="reaction-row">{QUICK.map(e=><button key={e} onClick={()=>onReact(e)}>{e}</button>)}<button onClick={onImageReact}>🖼️</button><button>+</button></div></div></article>}
function EmbedView({data}){if(data.provider==='youtube'&&data.embedUrl)return <iframe className="embed" src={data.embedUrl} title="YouTube" sandbox="allow-scripts allow-same-origin allow-presentation" allowFullScreen/>;if(data.provider==='custom'&&data.embedUrl)return <iframe className="embed" srcDoc={data.html} title="Embedded content" sandbox="allow-scripts allow-same-origin allow-presentation"/>;return <a className="link-card" href={data.url} target="_blank" rel="noreferrer"><Link2/><span>{data.url}</span></a>}
function PreviewModal({data,close,confirm}){return <div className="modal-backdrop"><div className="modal glass"><button className="close" onClick={close}><X/></button><h3>{data.embed?'Embed preview':'File preview'}</h3>{data.embed?<EmbedView data={data.embed}/>:data.file.type.startsWith('image/')?<img className="preview-image" src={data.url}/>:data.file.type.startsWith('video/')?<video className="preview-video" controls src={data.url}/>:data.file.type.startsWith('audio/')?<div className="audio-preview"><Music2/><b>{data.file.name}</b><audio controls src={data.url}/></div>:<div className="file-preview"><FileText/><b>{data.file.name}</b><small>{Math.round(data.file.size/1024)} KB</small></div>}<button className="primary" onClick={confirm}>{data.embed?'Send Embed':'Send File'}</button></div></div>}
function Panel({panel,setPanel,requests,handleRequest,onEmoji,onMusicUpload,music,setMusic,currentTrack,playing,playTrack,onWelcome,api}){if(panel==='emoji')return <div className="side-panel glass"><PanelHead title="Emoji" close={()=>setPanel(null)}/><div className="emoji-grid">{['😀','😂','💀','❤️','🔥','👍','😭','😎','🤯','🥹','✨','🎉','😮','🙌','🫡','🤝','👀','🚀','🧊','🗿','💯','🤣','😈','🙏'].map(e=><button key={e} onClick={()=>onEmoji(e)}>{e}</button>)}</div></div>;if(panel==='requests')return <div className="side-panel glass"><PanelHead title="Message Requests" close={()=>setPanel(null)}/>{requests.map(r=><div className="request"><Avatar p={r.sender}/><div><b>{r.sender.display_name}</b><small>@{r.sender.username}</small><p>{r.initial_message||'Wants to message you.'}</p><div><button className="primary small" onClick={()=>handleRequest(r.id,'accepted')}>Accept</button><button className="ghost small" onClick={()=>handleRequest(r.id,'declined')}>Decline</button></div></div></div>)}{!requests.length&&<div className="empty">No pending requests.</div>}</div>;if(panel==='settings')return <div className="side-panel glass"><PanelHead title="Settings" close={()=>setPanel(null)}/><div className="settings"><h4>Account</h4><p>Signed in as your Google account.</p><button className="ghost" onClick={()=>supabase.auth.signOut()}><LogOut/> Log out</button><h4>Background</h4><div className="bg-buttons"><button onClick={()=>document.body.classList.add('x')}>Aurora</button><button>Midnight</button><button>Ice</button></div><h4>Welcome Music</h4><input type="file" accept="audio/*" onChange={e=>e.target.files[0]&&onWelcome(e.target.files[0])}/><small>1–10 seconds. Browser autoplay rules may require a click before playback.</small></div></div>;if(panel==='music')return <div className="side-panel music-panel glass"><PanelHead title="Music Library" close={()=>setPanel(null)}/><label className="upload"><Upload/> Add music<input hidden type="file" accept="audio/*" multiple onChange={e=>setMusic([...music,...Array.from(e.target.files).map(f=>({name:f.name,url:URL.createObjectURL(f)}))])}/></label>{music.map(t=><div className={`track ${currentTrack?.name===t.name?'current':''}`} key={t.name}><Music2/><span>{t.name}</span><button onClick={()=>playTrack(t)}>{currentTrack?.name===t.name&&playing?<Pause/>:<Play/>}</button></div>)}</div>;if(panel==='gif')return <GifPanel api={api} sendGif={async(url)=>{await api('/api/conversations/'+window.__frostlinkActiveConversation+'/messages',{method:'POST',body:JSON.stringify({type:'gif',payload:{url}})});setPanel(null)}}/>;return <div className="side-panel glass"><PanelHead title={typeof panel==='string'?panel:'Panel'} close={()=>setPanel(null)}/><div className="empty">Feature panel ready for the selected tool.</div></div>}
function GifPanel({api,sendGif}){const[q,setQ]=useState(''),[items,setItems]=useState([]);return <div className="side-panel glass"><PanelHead title="GIFs" close={()=>location.reload()}/><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={async e=>{if(e.key==='Enter'){const x=await api('/api/giphy?q='+encodeURIComponent(q));setItems(x.data||[])}}} placeholder="Search GIFs"/></div><div className="gif-grid">{items.map(x=><button key={x.id} onClick={()=>sendGif(x.images.original.url)}><img src={x.images.fixed_width.url}/></button>)}</div></div>}
function PanelHead({title,close}){return <div className="panel-head"><h2>{title}</h2><button onClick={close}><X/></button></div>}
createRoot(document.getElementById('root')).render(<App/>);
