import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {io} from 'socket.io-client';
import {Search,Star,Settings,Plus,Smile,Send,Music2,Volume2,Image as ImageIcon,FileText,Link2,X,UserPlus,Inbox,LogOut,MoreHorizontal} from 'lucide-react';
import './styles.css';

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY);
const API=import.meta.env.VITE_API_URL||'http://localhost:3001';
const QUICK=['❤️','😂','👍','😮','💀','🔥','😭','✨'];
const fmt=d=>new Date(d).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
const fileType=f=>f.type.startsWith('image/')?'image':f.type.startsWith('video/')?'video':f.type.startsWith('audio/')?'sound':'file';

function App(){
 const [session,setSession]=useState(null),[profile,setProfile]=useState(undefined),[convos,setConvos]=useState([]),[active,setActive]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(''),[search,setSearch]=useState(''),[users,setUsers]=useState([]),[searchError,setSearchError]=useState(''),[requests,setRequests]=useState([]),[panel,setPanel]=useState(null),[preview,setPreview]=useState(null),[viewer,setViewer]=useState(null),[latest,setLatest]=useState(0),[nearBottom,setNearBottom]=useState(true),[themeBg,setThemeBg]=useState('aurora'),[reactionTarget,setReactionTarget]=useState(null),[starred,setStarred]=useState([]),[setupError,setSetupError]=useState('');
 const socket=useRef(null),listRef=useRef(null),fileRef=useRef(null),activeRef=useRef(null),nearRef=useRef(true),searchRef=useRef('');
 const token=()=>session?.access_token;
 const api=async(path,opt={})=>{const r=await fetch(API+path,{...opt,headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json',...(opt.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`Request failed (${r.status})`);return j};
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session)).catch(console.error);const {data}=supabase.auth.onAuthStateChange((_,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session)return;let dead=false;(async()=>{try{const x=await api('/api/profile');if(!dead)setProfile(x.profile)}catch(e){console.error('Profile load failed',e);if(!dead)setProfile(null)}try{const x=await api('/api/conversations');if(!dead)setConvos(x.conversations||[])}catch(e){console.error('Conversations load failed',e)}try{const x=await api('/api/message-requests');if(!dead)setRequests(x.requests||[])}catch(e){console.error('Requests load failed',e)}})();const s=io(API,{auth:{accessToken:session.access_token}});socket.current=s;s.on('message:new',m=>{if(m.conversation_id===activeRef.current){setMessages(old=>old.some(x=>x.id===m.id)?old:[...old,m]);if(nearRef.current)setTimeout(scrollBottom,40);else setLatest(n=>n+1)}loadConversations()});s.on('reaction:update',r=>setMessages(old=>old.map(m=>m.id===r.message_id?{...m,reactions:[...(m.reactions||[]).filter(q=>!(q.user_id===r.user_id&&q.kind===r.kind)),r]}:m)));return()=>{s.disconnect();socket.current=null}},[session]);
 useEffect(()=>{activeRef.current=active?.id||null;if(!active){setMessages([]);return}setLatest(0);loadMessages(active.id);socket.current?.emit('join-conversation',active.id);return()=>socket.current?.emit('leave-conversation',active.id)},[active?.id]);
 useEffect(()=>{const q=search.trim();searchRef.current=q;if(q.length<2){setUsers([]);setSearchError('');return}const t=setTimeout(async()=>{try{const x=await api('/api/users/search?q='+encodeURIComponent(q));if(searchRef.current===q)setUsers(x.users||[]);setSearchError('')}catch(e){console.error('User search failed',e);setUsers([]);setSearchError(e.message)}},250);return()=>clearTimeout(t)},[search]);
 async function loadConversations(){try{const x=await api('/api/conversations');setConvos(x.conversations||[]);return x.conversations||[]}catch(e){console.error(e);return []}}
 async function loadMessages(id){try{const x=await api(`/api/conversations/${id}/messages`);setMessages(x.messages||[]);requestAnimationFrame(scrollBottom)}catch(e){console.error('Messages load failed',e);setMessages([])}}
 function scrollBottom(){const e=listRef.current;if(e)e.scrollTo({top:e.scrollHeight,behavior:'smooth'});setLatest(0);setNearBottom(true);nearRef.current=true}
 function onScroll(){const e=listRef.current;if(!e)return;const n=e.scrollHeight-e.scrollTop-e.clientHeight<180;setNearBottom(n);nearRef.current=n;if(n)setLatest(0)}
 async function send(type='text',body=null,payload={}){if(!active){setPanel(null);return}if(type==='text'&&!text.trim())return;try{await api(`/api/conversations/${active.id}/messages`,{method:'POST',body:JSON.stringify({type,body:type==='text'?text.trim():body,payload})});if(type==='text')setText('');await loadConversations()}catch(e){alert(e.message)}}
 function readFile(file){return new Promise((resolve,reject)=>{if(file.size>1500000)return reject(new Error('For now, keep files under 1.5 MB. Larger persistent uploads can be added with Supabase Storage.'));const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Could not read file.'));r.readAsDataURL(file)})}
 async function chooseFile(file){if(!file)return;try{const data=await readFile(file);const type=fileType(file);if(reactionTarget){await api(`/api/messages/${reactionTarget}/reactions`,{method:'POST',body:JSON.stringify({kind:'image',value:data})});setReactionTarget(null);return}setPreview({file,data,type})}catch(e){alert(e.message)}}
 async function confirmFile(){if(!preview)return;try{await send(preview.type,null,{name:preview.file.name,size:preview.file.size,mime:preview.file.type,url:preview.data});setPreview(null)}catch(e){alert(e.message)}}
 async function react(id,emoji){try{await api(`/api/messages/${id}/reactions`,{method:'POST',body:JSON.stringify({kind:'emoji',value:emoji})})}catch(e){alert(e.message)}}
 function toggleStar(m){setStarred(old=>old.some(x=>x.id===m.id)?old.filter(x=>x.id!==m.id):[...old,m]);}
 async function requestUser(u){const initial=prompt(`Message to @${u.username} (optional):`)??'';try{await api('/api/message-requests',{method:'POST',body:JSON.stringify({recipient_id:u.id,initial_message:initial})});alert('Message request sent.');setSearch('');setUsers([])}catch(e){alert(e.message)}}
 async function handleRequest(id,action){try{const x=await api(`/api/message-requests/${id}/${action}`,{method:'POST'});const nextReq=await api('/api/message-requests');setRequests(nextReq.requests||[]);if(x.conversation_id){const list=await loadConversations();const c=list.find(q=>q.id===x.conversation_id);if(c)setActive(c)}}catch(e){alert(e.message)}}
 async function saveProfile(username,displayName){setSetupError('');try{const x=await api('/api/profile',{method:'POST',body:JSON.stringify({username,display_name:displayName})});setProfile(x.profile)}catch(e){setSetupError(e.message)}}
 async function embed(){const input=prompt('Paste a URL or iframe embed code:');if(!input)return;try{const x=await api('/api/embeds/parse',{method:'POST',body:JSON.stringify({input})});setPreview({embed:x.embed})}catch(e){alert(e.message)}}
 async function logout(){await supabase.auth.signOut();setProfile(undefined);setActive(null);setMessages([])}
 if(!session)return <Login/>;
 if(profile===undefined)return <div className="login bg-aurora"><div className="login-card glass"><div className="snow big">❄</div><h1>FROSTLINK</h1><p>Checking your profile…</p></div></div>;
 if(!profile)return <ProfileSetup user={session.user} error={setupError} onSave={saveProfile}/>;
 const currentName=active?.other?.display_name||active?.other?.username||active?.title||'Conversation';
 return <div className={`app bg-${themeBg}`}>
  <header className="topbar glass"><div className="brand"><div className="snow">❄</div><div><b>FROSTLINK</b><small>PRIVATE CONVERSATIONS</small></div></div><div className="top-actions"><span className="status"><i/> CONNECTED</span><button onClick={()=>setPanel('star')}><Star/></button><button onClick={()=>setPanel('requests')} className="icon-badge"><Inbox/>{requests.length>0&&<em>{requests.length}</em>}</button><button onClick={()=>setPanel('settings')}><Settings/></button></div></header>
  <main className="workspace glass"><aside className="sidebar"><div className="side-head"><h2>Messages</h2><button onClick={()=>setPanel('requests')}><Inbox/></button></div><div className="search"><Search/><input autoComplete="off" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search people or usernames…"/></div>{(users.length||searchError)&&<div className="user-results">{searchError?<div className="search-error">{searchError}</div>:users.length?users.map(u=><button key={u.id} onClick={()=>requestUser(u)}><Avatar p={u}/><span><b>{u.display_name}</b><small>@{u.username}</small></span><UserPlus/></button>):<div className="search-empty">No matching users.</div>}</div>}<div className="conversation-list">{convos.map(c=><button className={active?.id===c.id?'conversation active':'conversation'} key={c.id} onClick={()=>setActive(c)}><Avatar p={c.other}/><span className="conv-copy"><b>{c.other?.display_name||c.title||'Conversation'}</b><small>{c.last?.body||c.last?.type||'No messages yet'}</small></span><time>{c.last?.created_at?fmt(c.last.created_at):''}</time></button>)}{!convos.length&&<div className="empty">Search for a username to start a conversation.</div>}</div></aside>
  <section className="chat"><div className="chat-head"><div><h2>{currentName}</h2><small>{active?.other?`@${active.other.username}`:'Choose a conversation from the left'}</small></div><div className="chat-actions"><button title="Search"><Search/></button><button onClick={()=>setPanel('chat')}><MoreHorizontal/></button></div></div>
   <div className="messages" ref={listRef} onScroll={onScroll}>{messages.map(m=><Message key={m.id} m={m} me={m.sender_id===session.user.id} starred={starred.some(x=>x.id===m.id)} onStar={()=>toggleStar(m)} onReact={e=>react(m.id,e)} onImageReact={()=>{setReactionTarget(m.id);fileRef.current?.click()}} onOpen={setViewer}/>)}</div>
   {latest>0&&!nearBottom&&<button className="latest" onClick={scrollBottom}>↓ {latest} {latest===1?'message':'messages'}</button>}
   <div className="composer-wrap"><div className="composer"><button onClick={()=>fileRef.current?.click()} title="Files"><Plus/></button><button onClick={()=>setPanel('emoji')} title="Emoji"><Smile/></button><button onClick={()=>setPanel('gif')} title="GIF" className="gif-button"><span>GIF</span></button><button onClick={()=>fileRef.current?.click()} title="Image"><ImageIcon/></button><button onClick={()=>setPanel('sound')} title="Sounds"><Volume2/></button><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder={active?'Write a message…':'Select a conversation to start chatting…'} disabled={!active}/><button onClick={embed} title="Embed"><Link2/></button><button onClick={()=>setPanel('music')} title="Music"><Music2/></button><button className="send" onClick={()=>send()} disabled={!active||!text.trim()}><Send/></button></div><small>Enter sends · Shift+Enter adds a line · files, media, embeds and reactions supported</small></div>
  </section></main>
  <input ref={fileRef} type="file" multiple hidden onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)chooseFile(f)}}/>
  {panel&&<Panel panel={panel} close={()=>setPanel(null)} requests={requests} handleRequest={handleRequest} starred={starred} onEmoji={e=>{setText(t=>t+e);setPanel(null)}} setThemeBg={setThemeBg} logout={logout} api={api} sendGif={url=>{send('gif',null,{url});setPanel(null)}}/>}
  {preview&&<Preview data={preview} close={()=>setPreview(null)} confirm={preview.embed?()=>{send('embed',null,preview.embed);setPreview(null)}:confirmFile}/>} {viewer&&<div className="modal-backdrop viewer-backdrop" onClick={()=>setViewer(null)}><div className="image-viewer glass" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setViewer(null)}><X/></button><img src={viewer}/></div></div>}
 </div>
}

function Login(){return <div className="login bg-aurora"><div className="login-card glass"><div className="snow big">❄</div><h1>FROSTLINK</h1><p>Private conversations, media and moments.</p><button onClick={()=>supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}})}>Continue with Google</button><small>Secure sign-in powered by Supabase</small></div></div>}
function ProfileSetup({user,error,onSave}){const [name,setName]=useState(user.user_metadata?.full_name||user.user_metadata?.name||user.email?.split('@')[0]||'User'),[username,setUsername]=useState(''),[busy,setBusy]=useState(false);return <div className="login bg-aurora"><div className="login-card glass"><div className="snow big">❄</div><h1>WELCOME</h1><p>Choose your permanent FROSTLINK identity.</p><label className="setup-label">Display name<input value={name} onChange={e=>setName(e.target.value)} maxLength={60}/></label><label className="setup-label">Username<input value={username} onChange={e=>setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,''))} maxLength={24} placeholder="your_username"/><small>@username · 3–24 letters, numbers or underscores</small></label>{error&&<div className="setup-error">{error}</div>}<button disabled={busy||username.length<3||!name.trim()} onClick={async()=>{setBusy(true);await onSave(username,name);setBusy(false)}}>{busy?'Saving…':'Enter FROSTLINK'}</button></div></div>}
function Avatar({p}){return p?.avatar_url?<img className="avatar" src={p.avatar_url} alt=""/>:<div className="avatar fallback">{(p?.display_name||p?.username||'?')[0].toUpperCase()}</div>}
function Message({m,me,starred,onStar,onReact,onImageReact,onOpen}){const p=m.payload||{};return <article className={`msg ${me?'mine':'theirs'}`}><Avatar p={m.sender}/><div className="bubble-wrap"><div className="meta"><b>{m.sender?.display_name||'User'}</b><time>{fmt(m.created_at)}</time></div><div className="bubble">{m.type==='text'&&<p>{m.body}</p>}{m.type==='image'&&<img src={p.url} onClick={()=>onOpen(p.url)} alt=""/>}{m.type==='video'&&<video controls src={p.url}/>} {m.type==='sound'&&<div className="audio-card"><Volume2/><span>{p.name||'Audio'}</span><audio controls src={p.url}/></div>}{m.type==='file'&&<a className="file-card" href={p.url||'#'} target="_blank" rel="noreferrer"><FileText/><span>{p.name||'File'}</span></a>}{m.type==='gif'&&<img src={p.url} onClick={()=>onOpen(p.url)} alt="GIF"/>}{m.type==='embed'&&<EmbedView data={p}/>}</div><div className="message-tools"><div className="quick-reactions">{QUICK.map(e=><button key={e} title={`React ${e}`} onClick={()=>onReact(e)}>{e}</button>)}</div><button title="Image reaction" onClick={onImageReact}>🖼️</button><button className={starred?'star-active':''} title={starred?'Unstar message':'Star message'} onClick={onStar}><Star fill={starred?'currentColor':'none'}/></button></div>{m.reactions?.length>0&&<div className="reactions">{m.reactions.map(r=>r.kind==='image'?<button key={r.id} className="reaction-img" onClick={()=>onOpen(r.value)}><img src={r.value} alt="Reaction"/></button>:<button key={r.id} className="reaction-chip" onClick={()=>onReact(r.value)}>{r.value}</button>)}</div>}</div></article>}
function EmbedView({data}){if(data.provider==='youtube'&&data.embedUrl)return <iframe className="embed" src={data.embedUrl} title="YouTube" allowFullScreen/>;if(data.provider==='custom'&&data.embedUrl)return <iframe className="embed" srcDoc={data.html} title="Embedded content" sandbox="allow-scripts allow-same-origin allow-presentation"/>;return <a className="link-card" href={data.url} target="_blank" rel="noreferrer"><Link2/><span>{data.url}</span></a>}
function Preview({data,close,confirm}){return <div className="modal-backdrop"><div className="modal glass"><button className="close" onClick={close}><X/></button><h3>{data.embed?'Embed preview':'File preview'}</h3>{data.embed?<EmbedView data={data.embed}/>:data.type==='image'?<img className="preview-image" src={data.data} alt="Preview"/>:data.type==='video'?<video className="preview-video" controls src={data.data}/>:data.type==='sound'?<audio className="audio-preview" controls src={data.data}/>:<div className="file-preview"><FileText/><b>{data.file.name}</b><small>{Math.round(data.file.size/1024)} KB</small></div>}<button className="primary" onClick={confirm}>{data.embed?'Send Embed':'Send File'}</button></div></div>}
function Panel({panel,close,requests,handleRequest,starred,onEmoji,setThemeBg,logout,api,sendGif}){if(panel==='emoji')return <div className="side-panel glass"><PanelHead title="Emoji" close={close}/><div className="emoji-grid">{['😀','😂','💀','❤️','🔥','👍','😭','😎','🤯','🥹','✨','🎉','😮','🙌','🫡','🤝','👀','🚀','🧊','🗿','💯','🤣','😈','🙏'].map(e=><button key={e} onClick={()=>onEmoji(e)}>{e}</button>)}</div></div>;if(panel==='requests')return <div className="side-panel glass"><PanelHead title="Message Requests" close={close}/>{requests.map(r=><div className="request" key={r.id}><Avatar p={r.sender}/><div><b>{r.sender?.display_name}</b><small>@{r.sender?.username}</small><p>{r.initial_message||'Wants to message you.'}</p><div><button className="primary small" onClick={()=>handleRequest(r.id,'accepted')}>Accept</button><button className="ghost small" onClick={()=>handleRequest(r.id,'declined')}>Decline</button></div></div></div>)}{!requests.length&&<div className="empty">No pending requests.</div>}</div>;if(panel==='settings')return <div className="side-panel glass"><PanelHead title="Settings" close={close}/><div className="settings"><h4>Account</h4><p>Signed in with Google.</p><button className="ghost" onClick={logout}><LogOut/> Log out</button><h4>Background</h4><div className="bg-buttons"><button onClick={()=>setThemeBg('aurora')}>Aurora</button><button onClick={()=>setThemeBg('midnight')}>Midnight</button><button onClick={()=>setThemeBg('ice')}>Ice</button></div></div></div>;if(panel==='gif')return <GifPanel api={api} close={close} sendGif={sendGif}/>;if(panel==='star')return <div className="side-panel glass"><PanelHead title="Starred messages" close={close}/>{starred.length?starred.map(m=><button key={m.id} className="starred-item" onClick={close}><div><b>{m.sender?.display_name||'User'}</b><small>{m.type==='text'?m.body:(m.payload?.name||m.type)}</small></div><Star fill="currentColor"/></button>):<div className="empty">Star messages with the ☆ button under them. They will appear here for this session.</div>}</div>;return <div className="side-panel glass"><PanelHead title="FROSTLINK" close={close}/><div className="empty">This panel is ready. More tools can be added without blocking the chat.</div></div>}
function GifPanel({api,close,sendGif}){const [q,setQ]=useState(''),[items,setItems]=useState([]),[err,setErr]=useState('');async function search(){try{const x=await api('/api/giphy?q='+encodeURIComponent(q||'trending'));setItems(x.data||[]);setErr('')}catch(e){setErr(e.message)}}return <div className="side-panel glass"><PanelHead title="GIFs" close={close}/><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Search GIFs"/></div>{err&&<div className="search-error">{err}</div>}<div className="gif-grid">{items.map(x=><button key={x.id} onClick={()=>sendGif(x.images.original.url)}><img src={x.images.fixed_width.url} alt="GIF"/></button>)}</div></div>}
function PanelHead({title,close}){return <div className="panel-head"><h2>{title}</h2><button onClick={close}><X/></button></div>}
createRoot(document.getElementById('root')).render(<App/>);
