import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {io} from 'socket.io-client';
import {Search,Star,Settings,Plus,Smile,Send,Music2,Volume2,Image as ImageIcon,FileText,Link2,X,UserPlus,Inbox,LogOut,MoreHorizontal,Save,Pencil} from 'lucide-react';
import './styles.css';

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY);
const API=import.meta.env.VITE_API_URL||'http://localhost:3001';
const QUICK=['❤️','😂','👍','😮','💀','🔥','😭','✨'];
const MAX_FILE_SIZE=25*1024*1024;
const fmt=d=>new Date(d).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
const fileType=f=>f.type.startsWith('image/')?'image':f.type.startsWith('video/')?'video':f.type.startsWith('audio/')?'sound':'file';

function App(){
 const [session,setSession]=useState(null),[profile,setProfile]=useState(undefined),[convos,setConvos]=useState([]),[active,setActive]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(''),[search,setSearch]=useState(''),[users,setUsers]=useState([]),[searchError,setSearchError]=useState(''),[requests,setRequests]=useState([]),[outgoingRequests,setOutgoingRequests]=useState([]),[panel,setPanel]=useState(null),[preview,setPreview]=useState(null),[viewer,setViewer]=useState(null),[latest,setLatest]=useState(0),[nearBottom,setNearBottom]=useState(true),[themeBg,setThemeBg]=useState('aurora'),[reactionTarget,setReactionTarget]=useState(null),[starred,setStarred]=useState([]),[starredName,setStarredName]=useState('Starred'),[setupError,setSetupError]=useState(''),[dragging,setDragging]=useState(false);
 const socket=useRef(null),listRef=useRef(null),fileRef=useRef(null),activeRef=useRef(null),nearRef=useRef(true),searchRef=useRef(''),dragDepth=useRef(0);
 const token=()=>session?.access_token;
 const api=async(path,opt={})=>{const r=await fetch(API+path,{...opt,headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json',...(opt.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok){const err=new Error(j.error||`Request failed (${r.status})`);err.code=j.code;throw err}return j};
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session)).catch(console.error);const {data}=supabase.auth.onAuthStateChange((_,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session)return;let dead=false;(async()=>{try{const x=await api('/api/profile');if(!dead)setProfile(x.profile)}catch(e){console.error('Profile load failed',e);if(!dead)setProfile(null)}try{const x=await api('/api/conversations');if(!dead)setConvos(x.conversations||[])}catch(e){console.error('Conversations load failed',e)}try{const x=await api('/api/message-requests');if(!dead)setRequests(x.requests||[])}catch(e){console.error('Requests load failed',e)}loadOutgoingRequests();})();const s=io(API,{auth:{accessToken:session.access_token},transports:['websocket','polling'],reconnection:true,reconnectionAttempts:Infinity,reconnectionDelay:500,reconnectionDelayMax:4000});socket.current=s;const join=()=>{const id=activeRef.current;if(id)s.emit('join-conversation',id)};s.on('connect',join);s.on('reconnect',join);s.on('message:new',m=>{if(m.conversation_id===activeRef.current){setMessages(old=>old.some(x=>x.id===m.id)?old:[...old,m]);if(nearRef.current)setTimeout(scrollBottom,40);else setLatest(n=>n+1)}loadConversations()});s.on('reaction:update',r=>setMessages(old=>old.map(m=>m.id===r.message_id?{...m,reactions:[...(m.reactions||[]).filter(q=>!(q.user_id===r.user_id&&q.kind===r.kind)),r]}:m)));s.on('connect_error',e=>console.error('Realtime connection failed:',e.message));return()=>{s.removeAllListeners();s.disconnect();socket.current=null}},[session]);
 useEffect(()=>{activeRef.current=active?.id||null;if(!active){setMessages([]);setStarred([]);setStarredName('Starred');return}setLatest(0);loadMessages(active.id);loadStarred(active.id);const join=()=>socket.current?.emit('join-conversation',active.id);if(socket.current?.connected)join();return()=>socket.current?.emit('leave-conversation',active.id)},[active?.id]);
 useEffect(()=>{const q=search.trim().replace(/^@/,'').toLowerCase();searchRef.current=q;if(q.length<2){setUsers([]);setSearchError('');return}const t=setTimeout(async()=>{try{const x=await api('/api/users/search?q='+encodeURIComponent(q));if(searchRef.current===q)setUsers(x.users||[]);setSearchError('')}catch(e){console.error('User search failed',e);setUsers([]);setSearchError(e.message)}},250);return()=>clearTimeout(t)},[search]);
 async function loadOutgoingRequests(){try{const x=await api('/api/message-requests/outgoing');setOutgoingRequests(x.requests||[]);return x.requests||[]}catch(e){console.error('Outgoing requests load failed',e);return []}}async function loadConversations(){try{const x=await api('/api/conversations');setConvos(x.conversations||[]);return x.conversations||[]}catch(e){console.error(e);return []}}
 async function loadMessages(id){try{const x=await api(`/api/conversations/${id}/messages`);if(activeRef.current===id)setMessages(x.messages||[]);requestAnimationFrame(scrollBottom)}catch(e){console.error('Messages load failed',e);if(activeRef.current===id)setMessages([])}}
 async function loadStarred(id){try{const x=await api(`/api/starred-items?conversation_id=${encodeURIComponent(id)}`);if(activeRef.current===id){setStarred(x.items||[]);setStarredName(x.name||'Starred')}}catch(e){console.error('Starred messages load failed',e);if(activeRef.current===id){setStarred([]);setStarredName('Starred')}}}
 function scrollBottom(){const e=listRef.current;if(e)e.scrollTo({top:e.scrollHeight,behavior:'smooth'});setLatest(0);setNearBottom(true);nearRef.current=true}
 function jumpToMessage(id){const el=document.querySelector(`.messages .msg[data-message-id="${CSS.escape(id)}"]`);if(el){el.scrollIntoView({behavior:'smooth',block:'center'});el.classList.add('message-jump');setTimeout(()=>el.classList.remove('message-jump'),900)}}
 function onScroll(){const e=listRef.current;if(!e)return;const n=e.scrollHeight-e.scrollTop-e.clientHeight<180;setNearBottom(n);nearRef.current=n;if(n)setLatest(0)}
 async function send(type='text',body=null,payload={}){if(!active){setPanel(null);return false}if(type==='text'&&!text.trim())return false;try{await api(`/api/conversations/${active.id}/messages`,{method:'POST',body:JSON.stringify({type,body:type==='text'?text.trim():body,payload})});if(type==='text')setText('');await loadConversations();return true}catch(e){alert(e.message);return false}}
 function readFile(file){return new Promise((resolve,reject)=>{if(file.size>MAX_FILE_SIZE)return reject(new Error('File is too large. Maximum file size is 25 MB.'));const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Could not read file.'));r.readAsDataURL(file)})}
 async function chooseFile(file){if(!file)return;try{const data=await readFile(file);const type=fileType(file);if(reactionTarget){await api(`/api/messages/${reactionTarget}/reactions`,{method:'POST',body:JSON.stringify({kind:'image',value:data})});setReactionTarget(null);return}setPreview({file,data,type})}catch(e){alert(e.message)}}
 async function confirmFile(){if(!preview)return;try{await send(preview.type,null,{name:preview.file.name,size:preview.file.size,mime:preview.file.type,url:preview.data});setPreview(null)}catch(e){alert(e.message)}}
 function dragEnter(e){e.preventDefault();e.stopPropagation();if(!active||!e.dataTransfer?.types?.includes('Files'))return;dragDepth.current+=1;setDragging(true)}
 function dragOver(e){e.preventDefault();e.stopPropagation();if(active&&e.dataTransfer?.types?.includes('Files'))e.dataTransfer.dropEffect='copy'}
 function dragLeave(e){e.preventDefault();e.stopPropagation();dragDepth.current=Math.max(0,dragDepth.current-1);if(dragDepth.current===0)setDragging(false)}
 function dropFile(e){e.preventDefault();e.stopPropagation();dragDepth.current=0;setDragging(false);if(!active)return;const file=e.dataTransfer?.files?.[0];if(file)chooseFile(file)}
 async function react(id,emoji){try{await api(`/api/messages/${id}/reactions`,{method:'POST',body:JSON.stringify({kind:'emoji',value:emoji})})}catch(e){alert(e.message)}}
 async function toggleStar(m){try{await api('/api/starred-items',{method:'POST',body:JSON.stringify({message_id:m.id})});await loadStarred(activeRef.current)}catch(e){alert(e.message)}}
 async function saveMedia(m){const p=m.payload||{},url=p.url||p.embedUrl||p.original_url;if(!url)return;try{await api('/api/starred-items',{method:'POST',body:JSON.stringify({message_id:m.id,name:p.name||m.type,url})});await loadStarred(activeRef.current)}catch(e){alert(e.message)}}
 async function renameStarred(){if(!active)return;const next=(prompt('Rename starred section',starredName)||'').trim();if(!next||next===starredName)return;try{const x=await api('/api/starred-tab',{method:'PATCH',body:JSON.stringify({conversation_id:active.id,name:next})});setStarredName(x.name||next)}catch(e){alert(e.message)}}
 async function requestUser(u){const existingConversation=convos.find(c=>c.kind==='direct'&&c.other?.id===u.id);if(existingConversation){setActive(existingConversation);setSearch('');setUsers([]);return}const alreadySent=outgoingRequests.some(r=>r.recipient_id===u.id&&r.status==='pending');if(alreadySent){alert(`You already sent a message request to @${u.username}.`);return}const initial=prompt(`First message to @${u.username}:`);if(initial===null)return;const message=initial.trim();if(!message){alert('Your first message is required.');return}try{await api('/api/message-requests',{method:'POST',body:JSON.stringify({recipient_id:u.id,initial_message:message})});await loadOutgoingRequests();alert(`Message request sent to @${u.username}.`);setSearch('');setUsers([])}catch(e){if(e.code==='REQUEST_ALREADY_SENT'){await loadOutgoingRequests();alert(`You already sent a message request to @${u.username}.`);return}alert(e.message)}}
 async function handleRequest(id,action){try{const x=await api(`/api/message-requests/${id}/${action}`,{method:'POST'});setRequests(old=>old.filter(r=>r.id!==id));if(x.conversation_id){const list=await loadConversations();const c=list.find(q=>q.id===x.conversation_id);if(c)setActive(c);else await loadConversations()}setPanel(null)}catch(e){console.error('Message request action failed:',e);alert(e.message)}}
 async function saveProfile(username,displayName){setSetupError('');try{const x=await api('/api/profile',{method:'POST',body:JSON.stringify({username,display_name:displayName})});setProfile(x.profile)}catch(e){setSetupError(e.message)}}
 async function embed(){const input=prompt('Paste a URL or iframe embed code:');if(!input)return;try{const x=await api('/api/embeds/parse',{method:'POST',body:JSON.stringify({input})});setPreview({embed:x.embed})}catch(e){alert(e.message)}}
 async function logout(){await supabase.auth.signOut();setProfile(undefined);setActive(null);setMessages([])}
 if(!session)return <Login/>;
 if(profile===undefined)return <div className="login bg-aurora"><div className="login-card glass"><div className="snow big">❄</div><h1>FROSTLINK</h1><p>Checking your profile…</p></div></div>;
 if(!profile)return <ProfileSetup user={session.user} error={setupError} onSave={saveProfile}/>;
 const currentName=active?.other?.display_name||active?.other?.username||active?.title||'Conversation';
 const starredMessageIds=new Set(starred.filter(i=>i.kind==='message'||!i.kind).map(i=>(i.message||i).id));
 return <div className={`app bg-${themeBg}`}>
  <header className="topbar glass"><div className="brand"><div className="snow">❄</div><div><b>FROSTLINK</b><small>PRIVATE CONVERSATIONS</small></div></div><div className="top-actions"><span className="status"><i/> CONNECTED</span><button onClick={()=>active&&setPanel('star')} disabled={!active} title="Starred in this chat"><Star/></button><button onClick={()=>setPanel('requests')} className="icon-badge"><Inbox/>{requests.length>0&&<em>{requests.length}</em>}</button><button onClick={()=>setPanel('settings')}><Settings/></button></div></header>
  <main className="workspace glass"><aside className="sidebar"><div className="side-head"><h2>Messages</h2><button onClick={()=>setPanel('requests')}><Inbox/></button></div><div className="search"><Search/><input autoComplete="off" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search usernames…"/></div>{(users.length||searchError)&&<div className="user-results">{searchError?<div className="search-error">{searchError}</div>:users.length?users.map(u=>{const alreadySent=outgoingRequests.some(r=>r.recipient_id===u.id&&r.status==='pending');const existingConversation=convos.some(c=>c.kind==='direct'&&c.other?.id===u.id);return <button key={u.id} onClick={()=>requestUser(u)} disabled={alreadySent} className={alreadySent?'request-sent':''}><Avatar p={u}/><span><b>@{u.username}</b><small>{u.display_name}</small></span>{existingConversation?<span className="search-action">Open chat</span>:alreadySent?<span className="search-action">✓ Request sent</span>:<UserPlus/>}</button>}):<div className="search-empty">No matching usernames.</div>}</div>}<div className="conversation-list">{convos.map(c=><button className={active?.id===c.id?'conversation active':'conversation'} key={c.id} onClick={()=>setActive(c)}><Avatar p={c.other}/><span className="conv-copy"><b>{c.other?.display_name||c.title||'Conversation'}</b><small>{c.last?.body||c.last?.type||'No messages yet'}</small></span><time>{c.last?.created_at?fmt(c.last.created_at):''}</time></button>)}{!convos.length&&<div className="empty">Search for a username to start a conversation.</div>}</div></aside>
  <section className="chat" onDragEnter={dragEnter} onDragOver={dragOver} onDragLeave={dragLeave} onDrop={dropFile}><div className="chat-head"><div><h2>{currentName}</h2><small>{active?.other?`@${active.other.username}`:'Choose a conversation from the left'}</small></div><div className="chat-actions"><button title="Search"><Search/></button><button onClick={()=>setPanel('chat')}><MoreHorizontal/></button></div></div>
   <div className="messages" ref={listRef} onScroll={onScroll}>{messages.map(m=><Message key={m.id} m={m} me={m.sender_id===session.user.id} starred={starredMessageIds.has(m.id)} onStar={()=>toggleStar(m)} onSave={()=>saveMedia(m)} onReact={e=>react(m.id,e)} onImageReact={()=>{setReactionTarget(m.id);fileRef.current?.click()}} onOpen={setViewer}/>)}</div>
   {latest>0&&!nearBottom&&<button className="latest" onClick={scrollBottom}>↓ {latest} {latest===1?'message':'messages'}</button>}
   <div className="composer-wrap"><div className="composer"><button onClick={()=>fileRef.current?.click()} title="Files"><Plus/></button><button onClick={()=>setPanel('emoji')} title="Emoji"><Smile/></button><button onClick={()=>setPanel('gif')} title="GIF" className="gif-button"><span>GIF</span></button><button onClick={()=>fileRef.current?.click()} title="Image"><ImageIcon/></button><button onClick={()=>setPanel('sound')} title="Sounds"><Volume2/></button><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder={active?'Write a message…':'Select a conversation to start chatting…'} disabled={!active}/><button onClick={embed} title="Embed"><Link2/></button><button onClick={()=>setPanel('music')} title="Music"><Music2/></button><button className="send" onClick={()=>send()} disabled={!active||!text.trim()}><Send/></button></div><small>Enter sends · Shift+Enter adds a line · files, media, embeds and reactions supported</small></div>
  </section></main>
  <input ref={fileRef} type="file" multiple hidden onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)chooseFile(f)}}/>
  {dragging&&<div className="drop-overlay"><div className="drop-card glass"><div className="drop-icon">❄</div><strong>drop it in the frost</strong><small>Release to add the file to this chat</small></div></div>}
  {panel&&<Panel panel={panel} close={()=>setPanel(null)} requests={requests} handleRequest={handleRequest} starred={starred} starredName={starredName} onRename={renameStarred} onEmoji={e=>{setText(t=>t+e);setPanel(null)}} setThemeBg={setThemeBg} logout={logout} api={api} sendGif={async url=>{if(await send('gif',null,{url}))setPanel(null)}} jumpToMessage={id=>{setPanel(null);requestAnimationFrame(()=>jumpToMessage(id))}} onSave={saveMedia}/>} 
  {preview&&<Preview data={preview} close={()=>setPreview(null)} confirm={preview.embed?async()=>{if(await send('embed',null,preview.embed))setPreview(null)}:confirmFile}/>} {viewer&&<div className="modal-backdrop viewer-backdrop" onClick={()=>setViewer(null)}><div className="image-viewer glass" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setViewer(null)}><X/></button><img src={viewer} alt="Preview"/></div></div>}
 </div>
}

function Login(){return <div className="login bg-aurora"><div className="login-card glass"><div className="snow big">❄</div><h1>FROSTLINK</h1><p>Private conversations, media and moments.</p><button onClick={()=>supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin}})}>Continue with Google</button><small>Secure sign-in powered by Supabase</small></div></div>}
function ProfileSetup({user,error,onSave}){const [name,setName]=useState(user.user_metadata?.full_name||user.user_metadata?.name||user.email?.split('@')[0]||'User'),[username,setUsername]=useState(''),[busy,setBusy]=useState(false);return <div className="login bg-aurora"><div className="login-card glass"><div className="snow big">❄</div><h1>WELCOME</h1><p>Choose your permanent FROSTLINK identity.</p><label className="setup-label">Display name<input value={name} onChange={e=>setName(e.target.value)} maxLength={60}/></label><label className="setup-label">Username<input value={username} onChange={e=>setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,''))} maxLength={24} placeholder="your_username"/><small>@username · 3–24 letters, numbers or underscores</small></label>{error&&<div className="setup-error">{error}</div>}<button disabled={busy||username.length<3||!name.trim()} onClick={async()=>{setBusy(true);await onSave(username,name);setBusy(false)}}>{busy?'Saving…':'Enter FROSTLINK'}</button></div></div>}
function Avatar({p}){return p?.avatar_url?<img className="avatar" src={p.avatar_url} alt=""/>:<div className="avatar fallback">{(p?.display_name||p?.username||'?')[0].toUpperCase()}</div>}
function Message({m,me,starred,onStar,onSave,onReact,onImageReact,onOpen}){const p=m.payload||{},saveUrl=p.url||p.embedUrl||p.original_url;return <article data-message-id={m.id} className={`msg ${me?'mine':'theirs'}`}><Avatar p={m.sender}/><div className="bubble-wrap"><div className="meta"><b>{m.sender?.display_name||'User'}</b><time>{fmt(m.created_at)}</time></div><div className="bubble">{m.type==='text'&&<p>{m.body}</p>}{m.type==='image'&&<img src={p.url} onClick={()=>onOpen(p.url)} alt=""/>}{m.type==='video'&&<video controls src={p.url}/>} {m.type==='sound'&&<div className="audio-card"><Volume2/><span>{p.name||'Audio'}</span><audio controls src={p.url}/></div>}{m.type==='file'&&<a className="file-card" href={p.url||'#'} target="_blank" rel="noreferrer"><FileText/><span>{p.name||'File'}</span></a>}{m.type==='gif'&&<img src={p.url} onClick={()=>onOpen(p.url)} alt="GIF"/>}{m.type==='embed'&&<EmbedView data={p}/>}</div><div className="message-tools"><div className="quick-reactions">{QUICK.map(e=><button key={e} title={`React ${e}`} onClick={()=>onReact(e)}>{e}</button>)}</div><button title="Image reaction" onClick={onImageReact}>🖼️</button>{(m.type==='image'||m.type==='video'||m.type==='embed')&&saveUrl&&<button title="Save to this chat" onClick={onSave}><Save/></button>}<button className={starred?'star-active':''} title={starred?'Unstar message':'Star message'} onClick={onStar}><Star fill={starred?'currentColor':'none'}/></button></div>{m.reactions?.length>0&&<div className="reactions">{m.reactions.map(r=>r.kind==='image'?<button key={r.id} className="reaction-img" onClick={()=>onOpen(r.value)}><img src={r.value} alt="Reaction"/></button>:<button key={r.id} className="reaction-chip" onClick={()=>onReact(r.value)}>{r.value}</button>)}</div>}</div></article>}
function EmbedView({data}){if(data.provider==='youtube'&&data.embedUrl)return <iframe className="embed" src={data.embedUrl} title="YouTube" allowFullScreen/>;if(data.provider==='custom'&&data.embedUrl)return <iframe className="embed" srcDoc={data.html} title="Embedded content" sandbox="allow-scripts allow-same-origin allow-presentation"/>;return <a className="link-card" href={data.url} target="_blank" rel="noreferrer"><Link2/><span>{data.url}</span></a>}
function Preview({data,close,confirm}){return <div className="modal-backdrop"><div className="modal glass"><button className="close" onClick={close}><X/></button><h3>{data.embed?'Embed preview':'File preview'}</h3>{data.embed?<EmbedView data={data.embed}/>:data.type==='image'?<img className="preview-image" src={data.data} alt="Preview"/>:data.type==='video'?<video className="preview-video" controls src={data.data}/>:data.type==='sound'?<audio className="audio-preview" controls src={data.data}/>:<div className="file-preview"><FileText/><b>{data.file.name}</b><small>{Math.round(data.file.size/1024)} KB · max 25 MB</small></div>}<button className="primary" onClick={confirm}>{data.embed?'Send Embed':'Send File'}</button></div></div>}
function Panel({panel,close,requests,handleRequest,starred,starredName,onRename,onEmoji,setThemeBg,logout,api,sendGif,jumpToMessage,onSave}){if(panel==='emoji')return <div className="side-panel glass"><PanelHead title="Emoji" close={close}/><div className="emoji-grid">{['😀','😂','💀','❤️','🔥','👍','😭','😎','🤯','🥹','✨','🎉','😮','🙌','🫡','🤝','👀','🚀','🧊','🗿','💯','🤣','😈','🙏'].map(e=><button key={e} onClick={()=>onEmoji(e)}>{e}</button>)}</div></div>;if(panel==='requests')return <div className="side-panel glass"><PanelHead title="Message Requests" close={close}/>{requests.map(r=><div className="request" key={r.id}><Avatar p={r.sender}/><div><b>@{r.sender?.username}</b><small>{r.sender?.display_name}</small><p>{r.initial_message||'Wants to message you.'}</p><div><button className="primary small" onClick={()=>handleRequest(r.id,'accepted')}>Accept</button><button className="ghost small" onClick={()=>handleRequest(r.id,'declined')}>Decline</button></div></div></div>)}{!requests.length&&<div className="empty">No pending requests.</div>}</div>;if(panel==='settings')return <div className="side-panel glass"><PanelHead title="Settings" close={close}/><div className="settings"><h4>Account</h4><p>Signed in with Google.</p><button className="ghost" onClick={logout}><LogOut/> Log out</button><h4>Background</h4><div className="bg-buttons"><button onClick={()=>setThemeBg('aurora')}>Aurora</button><button onClick={()=>setThemeBg('midnight')}>Midnight</button><button onClick={()=>setThemeBg('ice')}>Ice</button></div></div></div>;if(panel==='gif')return <GifPanel api={api} close={close} sendGif={sendGif}/>;if(panel==='star')return <div className="side-panel glass"><div className="panel-head"><h2>{starredName}</h2><div style={{display:'flex',gap:5}}><button title="Rename starred section" onClick={onRename}><Pencil/></button><button title="Close" onClick={close}><X/></button></div></div>{starred.length?starred.map(item=>{const m=item.message||item;const when=m.created_at?new Date(m.created_at).toLocaleString():'';return <button key={item.id||m.id} className="starred-item" title={when} onClick={()=>jumpToMessage(m.id)}><div><b>{m.sender?.display_name||'User'}</b><small>{item.kind==='save'?'Saved · ':''}{m.type==='text'?m.body:(m.payload?.name||item.content?.name||m.type)}</small></div><Star fill="currentColor"/></button>}):<div className="empty">No starred messages in this chat yet.</div>}</div>;return <div className="side-panel glass"><PanelHead title="FROSTLINK" close={close}/><div className="empty">This panel is ready. More tools can be added without blocking the chat.</div></div>}
function GifPanel({api,close,sendGif}){const [q,setQ]=useState(''),[items,setItems]=useState([]),[err,setErr]=useState('');async function search(){try{const x=await api('/api/giphy?q='+encodeURIComponent(q||'trending'));setItems(x.data||[]);setErr('')}catch(e){setErr(e.message)}}return <div className="side-panel glass"><PanelHead title="GIFs" close={close}/><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Search GIFs"/></div>{err&&<div className="search-error">{err}</div>}<div className="gif-grid">{items.map(x=><button key={x.id} onClick={()=>sendGif(x.images.original.url)}><img src={x.images.fixed_width.url} alt="GIF"/></button>)}</div></div>}
function PanelHead({title,close}){return <div className="panel-head"><h2>{title}</h2><button onClick={close}><X/></button></div>}
createRoot(document.getElementById('root')).render(<App/>);
